import { StyleSheet } from "react-native";
import { Colors } from "./Colors";

export const globalStyles = StyleSheet.create({
  button: {
    padding: 10,
    backgroundColor: Colors.PRIMARY,
    width: 140,
    height: 40,
  },
  buttonText: {
    color: "#eee",
    fontSize: 16,
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  card: {
    position: "absolute",
    flex: 1,
    bottom: 120,
    left: 10,
    right: 10,
    height: 150,
    justifyContent: "space-between",
    backgroundColor: "#fff",
    zIndex: 100,
    borderRadius: 20,
    padding: 10,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  card2: {
    position: "absolute",
    flex: 1,
    bottom: 20,
    left: 10,
    right: 10,
    height: 150,
    justifyContent: "space-between",
    backgroundColor: "#fff",
    zIndex: 100,
    borderRadius: 20,
    padding: 10,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  cardBigger: {
    position: "absolute",
    flex: 1,
    bottom: 120,
    left: 10,
    right: 10,
    height: 255,
    justifyContent: "space-between",
    backgroundColor: "#fff",
    zIndex: 100,
    borderRadius: 20,
    padding: 10,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  cardButtons: {
    width: 60,
    height: 60,
    zIndex: 100,
    borderRadius: 30,
    padding: 10,
    shadowColor: "#000",
    justifyContent: "center",
    alignItems: "center",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  searchListContainer: {
    position: "absolute",
    bottom: 60,
    zIndex: 150,
    height: 120,
    backgroundColor: "white",
    borderRadius: 20,
    width: "100%",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  searchListContainer2: {
    position: "absolute",
    bottom: -120,
    zIndex: 150,
    height: 120,
    backgroundColor: "white",
    borderRadius: 20,
    width: "100%",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
});
